In [2]:
#Multiclass logistic regression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df=pd.read_csv("cyber_attack_data.csv")
df.head(15)

,src_packet_rate,dst_packet_rate,avg_payload_size,connection_duration,tcp_flag_count,avg_interarrival_time,failed_login_attempts,unusual_port_activity_score,session_entropy,avg_response_delay,attack_type
0,-1.286132,-0.648334,1.044115,-0.469715,0.789859,-0.083727,-1.647309,-1.316412,1.011910,-0.898063,2
1,-0.222224,2.083232,1.191114,-1.354527,-0.956992,1.696028,-1.070406,0.981403,-1.628798,1.377594,0
2,-0.431963,0.375745,-1.370334,0.819214,0.345243,1.389447,-1.904130,1.292602,0.925545,0.232705,0
3,-0.912633,0.986988,-0.690042,2.014628,-0.442260,0.590347,-1.819353,1.560938,0.823755,0.517762,0
4,-0.367056,1.667892,0.879172,2.214276,1.846338,-0.894047,1.543838,0.931103,-1.015210,1.061845,1
5,-1.874443,2.435431,1.066057,-1.496395,-1.290523,0.183384,-0.253859,0.751247,-0.686269,1.120212,0
6,-0.190443,2.095370,-1.347873,-0.031716,0.218323,-0.868269,1.153814,0.634842,-1.937976,1.364962,1
7,-0.392031,1.993144,0.026450,1.240267,-0.684384,-0.875844,0.840978,1.205214,-1.186506,1.289973,0
8,-1.717666,-0.065893,-1.846918,0.692185,0.873618,0.247292,2.558338,-0.421193,1.377519,-0.564467,2
9,0.851120,1.258551,-0.222734,1.268347,-0.214751,-0.137340,1.987766,1.376867,-1.313879,1.177652,1


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   src_packet_rate              1000 non-null   float64
 1   dst_packet_rate              1000 non-null   float64
 2   avg_payload_size             1000 non-null   float64
 3   connection_duration          1000 non-null   float64
 4   tcp_flag_count               1000 non-null   float64
 5   avg_interarrival_time        1000 non-null   float64
 6   failed_login_attempts        1000 non-null   float64
 7   unusual_port_activity_score  1000 non-null   float64
 8   session_entropy              1000 non-null   float64
 9   avg_response_delay           1000 non-null   float64
 10  attack_type                  1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [6]:
X=df.drop("attack_type", axis=1)
y=df["attack_type"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=34)

In [7]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

In [8]:
y_pred

array([0, 2, 0, 1, 1, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2,
       1, 0, 2, 0, 2, 0, 0, 2, 1, 1, 2, 1, 2, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       0, 2, 1, 1, 0, 1, 1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 0, 2, 1, 2, 0, 0, 2, 0, 2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 2, 0, 0,
       0, 2, 1, 2, 1, 2, 2, 0, 2, 2, 1, 1, 1, 2, 2, 1, 1, 0, 0, 1, 0, 0,
       2, 2, 2, 0, 0, 2, 2, 1, 0, 0, 0, 1, 0, 2, 0, 1, 1, 2, 0, 1, 0, 1,
       1, 2, 2, 1, 2, 1, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 1,
       1, 1, 0, 2, 0, 0, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 0, 0,
       0, 0, 1, 1, 0, 2, 2, 2, 0, 2, 1, 1, 2, 2, 2, 2, 1, 0, 1, 1, 1, 1,
       0, 2, 2, 1, 0, 1, 2, 0, 1, 2, 1, 2, 2, 0, 1, 0, 0, 1, 2, 1, 0, 1,
       1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1,
       1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 0, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1,
       2, 1, 0, 0, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 2, 2, 1, 2,
       1, 0, 2, 0, 2, 2, 2, 0, 1, 2, 1, 2, 1, 1])

In [9]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
score=accuracy_score(y_pred, y_test)
print("score:", score)
print("Classification Report:")
print(classification_report(y_pred, y_test))
print("Confusion Matrix:")
print(confusion_matrix(y_pred, y_test))

score: 0.7933333333333333
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.90      0.85        86
           1       0.76      0.75      0.75       106
           2       0.82      0.76      0.79       108

    accuracy                           0.79       300
   macro avg       0.79      0.80      0.80       300
weighted avg       0.79      0.79      0.79       300

Confusion Matrix:
[[77  4  5]
 [14 79 13]
 [ 5 21 82]]


In [11]:
penalty=["l1","l2", "elasticnet"]
c_values=[100,10,1,0.1,0.01]
solver=[ "newton-cg", "lbfgs","liblinear", "sag", "saga", "newton-cholesky"]

In [12]:
params=dict(penalty=penalty, C=c_values, solver=solver)
from sklearn.model_selection import GridSearchCV, StratifiedKFold
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model, param_grid=params, cv=cv, scoring="accuracy", n_jobs=-1)
grid.fit(X_train, y_train)

c:\Users\sudet\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning: 
275 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\sudet\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\sudet\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sudet\AppD

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",LogisticRegression()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'accuracy'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",StratifiedKFo...shuffle=False)
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and parameter candida

In [13]:
grid.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}

In [14]:
grid.best_score_

np.float64(0.7957142857142857)

In [15]:
y_pred_grid=grid.predict(X_test)

In [17]:
score=accuracy_score(y_pred_grid, y_test)
print("score:", score)
print("Classification Report:")
print(classification_report(y_pred_grid, y_test))
print("Confusion Matrix:")
print(confusion_matrix(y_pred_grid, y_test))

score: 0.7966666666666666
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.90      0.85        86
           1       0.77      0.75      0.76       106
           2       0.82      0.76      0.79       108

    accuracy                           0.80       300
   macro avg       0.80      0.80      0.80       300
weighted avg       0.80      0.80      0.80       300

Confusion Matrix:
[[77  3  6]
 [14 80 12]
 [ 5 21 82]]


In [18]:
#one vs rest
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier
ovomodel=OneVsOneClassifier(LogisticRegression())

In [ ]:
ovrmodel=OneVsRestClassifier(LogisticRegression())

In [22]:
ovomodel.fit(X_train, y_train)
y_pred_ovo=ovomodel.predict(X_test)
score_ovo=accuracy_score(y_pred_ovo, y_test)
print("One vs One score:", score_ovo)
print("One vs One Classification Report:")
print(classification_report(y_pred_ovo, y_test))
print("One vs One Confusion Matrix:")
print(confusion_matrix(y_pred_ovo, y_test))

One vs One score: 0.79
One vs One Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.87      0.83        87
           1       0.74      0.75      0.75       102
           2       0.84      0.76      0.80       111

    accuracy                           0.79       300
   macro avg       0.79      0.80      0.79       300
weighted avg       0.79      0.79      0.79       300

One vs One Confusion Matrix:
[[76  6  5]
 [14 77 11]
 [ 6 21 84]]


In [23]:
ovrmodel.fit(X_train, y_train)
y_pred_ovr=ovrmodel.predict(X_test)
score_ovr=accuracy_score(y_pred_ovr, y_test)
print("One vs Rest score:", score_ovr)
print("One vs Rest Classification Report:")
print(classification_report(y_pred_ovr, y_test))
print("One vs Rest Confusion Matrix:")
print(confusion_matrix(y_pred_ovr, y_test))

One vs Rest score: 0.7933333333333333
One vs Rest Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.91      0.85        85
           1       0.75      0.76      0.75       103
           2       0.83      0.74      0.78       112

    accuracy                           0.79       300
   macro avg       0.79      0.80      0.80       300
weighted avg       0.79      0.79      0.79       300

One vs Rest Confusion Matrix:
[[77  3  5]
 [13 78 12]
 [ 6 23 83]]
